GET http://localhost:3000/products

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Product 1 description",
  "image_url": "https://via.placeholder.com/150",
  "price": 100
}

###
GET http://localhost:3000/orders

###
POST http://localhost:3000/orders
Content-Type: application/json

{
  "items": [
    {
      "product_id": "028ae015-1ddb-480a-9f1c-1c99a85a66a2",
      "quantity": 1
    },
    {
      "product_id": "0ed803c9-f5a7-47ea-a4e3-038a9d77ac75",
      "quantity": 4
    }
    
  ],
  "card_hash": "1234678"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "john",
  "password": "changeme"
}